# This file was generated by GoReleaser. DO NOT EDIT.
cask "kiwi" do
  version "0.1.3"

  on_macos do
    on_arm do
      sha256 "4ab1800b0c512aa05472c2cbc75597920bb3fc4ec393874e6d4b95a7e23b721b"
      url "https://github.com/oscar1223/kiwi/releases/download/v#{version}/kiwi_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "0ba129b0d4bb606cbf5c39cc76ac275cdc54e5582854fcbe7ebfa8653f45d0d6"
      url "https://github.com/oscar1223/kiwi/releases/download/v#{version}/kiwi_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "e6fd9a7fe8485ff16deb0fea1d9891d5eb8e734f092f91bd6b910ac2702e1556"
      url "https://github.com/oscar1223/kiwi/releases/download/v#{version}/kiwi_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "39d6b179d3dc4d203b1e95bd2483b1c08f9141716f8bee5f4782a5919a707f3e"
      url "https://github.com/oscar1223/kiwi/releases/download/v#{version}/kiwi_linux_amd64.tar.gz"
    end
  end

  name "kiwi"
  desc "Agente de código local-first para la terminal"
  homepage "https://github.com/oscar1223/kiwi"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "kiwi"

  postflight do
    # El binario no está firmado por Apple: quitamos la cuarentena
    # que macOS le pone a todo lo bajado, o Gatekeeper lo bloquea.
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/kiwi"]
    end
  end

  # No zap stanza required
end
