# This file was generated by GoReleaser. DO NOT EDIT.
cask "kiwi" do
  version "0.1.0"

  on_macos do
    on_arm do
      sha256 "12456359609fc5d08bfc9b787783fef88a38dfa7f77189c87c6b336426844c17"
      url "https://github.com/oscar1223/kiwi/releases/download/v0.1.0/kiwi_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "55e1f80337f2bd472d72136961c40f127f55d4762ab3d8ac469c8014501485d4"
      url "https://github.com/oscar1223/kiwi/releases/download/v0.1.0/kiwi_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "6f024dbd17aa1b0ac7c041b5df78e52dc8f9d528e6f257c5b6d9f03b97a1b7cc"
      url "https://github.com/oscar1223/kiwi/releases/download/v0.1.0/kiwi_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "c2b1c4208e14a5d0b1bb47ec64c808b58ad8c785a43b4b619e0cdc9d5ec3784b"
      url "https://github.com/oscar1223/kiwi/releases/download/v0.1.0/kiwi_linux_amd64.tar.gz"
    end
  end

  name "kiwi"
  desc "Agente de código local-first para la terminal"
  homepage "https://github.com/oscar1223/kiwi"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "kiwi"

  postflight do
    # El binario no está firmado por Apple: quitamos la cuarentena
    # que macOS le pone a todo lo bajado, o Gatekeeper lo bloquea.
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/kiwi"]
    end
  end

  # No zap stanza required
end
