# This file was generated by GoReleaser. DO NOT EDIT.
cask "kiwi" do
  postflight_steps do
    on_macos do
      run "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "{{staged_path}}/kiwi"], must_succeed: false
    end
  end

  version "0.2.1"

  on_macos do
    on_arm do
      sha256 "0a47c2e2e6c9bed81e3ed7adc2a07a5ba0a8e737b48836c002a6b8600b5a55d8"
      url "https://github.com/oscar1223/kiwi/releases/download/v#{version}/kiwi_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "8f9893a8ef3c213baf66a3192ba46b0bf80d7566b6075be20a51714445d74f73"
      url "https://github.com/oscar1223/kiwi/releases/download/v#{version}/kiwi_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "309c36b298aa586d6fe67148df03c43406085de414f634654efb7afce3811ab6"
      url "https://github.com/oscar1223/kiwi/releases/download/v#{version}/kiwi_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "11e1806d431b4f564ac1e63758125e8fb064c47c7877373dfb56af823168360d"
      url "https://github.com/oscar1223/kiwi/releases/download/v#{version}/kiwi_linux_amd64.tar.gz"
    end
  end

  name "kiwi"
  desc "Agente de código local-first para la terminal"
  homepage "https://github.com/oscar1223/kiwi"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "kiwi"

  # No zap stanza required
end
